apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-service
  template:
    metadata:
      labels:
        app: ocr-service
    spec:
      containers:
        - name: ocr-service
          image: mspawanranjith/ocr-service:latest
          # resources:
          #   limits:
          #     memory: "1024Mi"
          #     cpu: "1000m"
          env:
            - name: TESSERACT_PATH
              value: /usr/bin/tesseract
            - name: KAFKA_SECRET_KEY
              value: pqfV+6B+nDwtrxr0GckMlrqofW5fW/kLPvWL83w+oZoPvkzwOzl5f/rhJbdYJOTn
            - name: MINIO_USER
              value: rootuser
            - name: MINIO_PASSWD
              value: rootpass123
            - name: MINIO_HOST
              value: minio:9000
